function setMessage() {
    const verses = [
        "Eres la luz que ilumina mis días,",
        "Eres el susurro en mis sueños.",
        "Tu sonrisa es el sol que calienta mi corazón.",
        "En tus ojos encuentro mi hogar.",
        "Cada día a tu lado es un regalo.",
        "Tu amor es la melodía de mi vida.",
        "Eres la estrella que guía mi camino.",
        "Junto a ti, cada momento es eterno.",
        "Eres la inspiración de mis versos.",
        "Contigo, el mundo es más bello.",
        "Cada amanecer a tu lado es una bendición.",
        "Tu voz es la música que calma mi alma.",
        "Eres el poema que siempre quise escribir.",
        "Contigo, mis sueños se hacen realidad.",
        "Eres la flor que adorna mi jardín.",
        "Tu risa es la brisa que refresca mi día.",
        "Eres el sol que ilumina mi oscuridad.",
        "Tu presencia hace que mi vida sea completa.",
        "Eres el tesoro más valioso que he encontrado.",
        "Contigo, la vida es un cuento de hadas.",
        "Eres la razón por la que sonrío cada día.",
        "Tu amor es el abrigo en mis días fríos.",
        "Eres el faro que guía mi barco en la noche.",
        "Tu mirada es el espejo de mi alma.",
        "Eres el refugio donde mi corazón encuentra paz.",
        "Tu cariño es el bálsamo que cura mis heridas.",
        "Eres el horizonte que quiero alcanzar.",
        "Tu mano es el ancla que me mantiene firme.",
        "Eres la magia que hace que todo sea posible.",
        "Contigo, el tiempo se detiene y la felicidad florece.",
        "Eres el verso más hermoso de mi canción.",
        "Tu amor es el motor que impulsa mi vida.",
        "Eres el arcoíris que pinta mis días grises.",
        "Tu risa es la melodía que alegra mi corazón.",
        "Eres la luna que ilumina mis noches más oscuras.",
        "Tu presencia es el regalo que siempre esperé.",
        "Eres la chispa que enciende mi vida.",
        "Tu sonrisa es el amanecer que despierta mi corazón.",
        "Eres la brisa que acaricia mi alma.",
        "Tu abrazo es el refugio donde encuentro paz.",
        "Eres el mar donde quiero navegar eternamente.",
        "Tu amor es el fuego que mantiene viva mi pasión.",
        "Eres el sueño del que nunca quiero despertar.",
        "Tu mirada es el mapa que guía mi camino.",
        "Eres la canción que mi corazón canta todos los días.",
        "Tu risa es el sol que ilumina mis días nublados.",
        "Eres la estrella que brilla en mi cielo nocturno.",
        "Tu amor es el puente que une nuestras almas.",
        "Eres el latido que mantiene vivo mi corazón.",
        "Tu presencia es el aire que respiro.",
        "Eres la flor que perfuma mi vida.",
        "Tu amor es la fuerza que me impulsa a seguir.",
        "Eres el libro que nunca me canso de leer.",
        "Tu voz es la melodía que alegra mis días.",
        "Eres la luz que guía mis pasos.",
        "Tu sonrisa es el refugio donde encuentro felicidad.",
        "Eres el abrazo que siempre anhelo.",
        "Tu amor es el faro que ilumina mi vida.",
        "Eres el sueño que nunca quiero dejar de soñar.",
        "Tu presencia es el sol que calienta mi corazón.",
        "Eres la brisa que refresca mi alma.",
        "Tu amor es el abrigo que me protege del frío.",
        "Eres la luna que ilumina mis noches.",
        "Tu sonrisa es la luz que ilumina mi día.",
        "Eres el refugio donde encuentro paz y amor.",
        "Tu presencia es el regalo que siempre esperé.",
        "Eres el mar donde quiero navegar eternamente.",
        "Tu amor es la fuerza que me impulsa a seguir adelante.",
        "Eres la estrella que ilumina mi camino.",
        "Tu mirada es el espejo donde veo mi alma.",
        "Eres la luz que ilumina mi oscuridad.",
        "Tu risa es la melodía que alegra mi corazón.",
        "Eres el amanecer que despierta mis días.",
        "Tu voz es la música que calma mi alma.",
        "Eres el sueño del que nunca quiero despertar.",
        "Tu amor es el motor que impulsa mi vida.",
        "Eres el horizonte que quiero alcanzar.",
        "Tu presencia es el ancla que me mantiene firme.",
        "Eres la chispa que enciende mi vida.",
        "Tu sonrisa es el sol que ilumina mis días.",
        "Eres la brisa que acaricia mi alma.",
        "Tu abrazo es el refugio donde encuentro paz.",
        "Eres el mar donde quiero navegar eternamente.",
        "Tu amor es el fuego que mantiene viva mi pasión.",
        "Eres el sueño del que nunca quiero despertar.",
        "Tu mirada es el mapa que guía mi camino.",
        "Eres la canción que mi corazón canta todos los días.",
        "Tu risa es el sol que ilumina mis días nublados.",
        "Eres la estrella que brilla en mi cielo nocturno.",
        "Tu amor es el puente que une nuestras almas.",
        "Eres el latido que mantiene vivo mi corazón.",
        "Tu presencia es el aire que respiro.",
        "Eres la flor que perfuma mi vida.",
        "Tu amor es la fuerza que me impulsa a seguir.",
        "Eres el libro que nunca me canso de leer.",
        "Tu voz es la melodía que alegra mis días.",
        "Eres la luz que guía mis pasos.",
        "Tu sonrisa es el refugio donde encuentro felicidad.",
        "Eres el abrazo que siempre anhelo.",
        "Tu amor es el faro que ilumina mi vida.",
        "Eres el sueño que nunca quiero dejar de soñar.",
        "Tu presencia es el sol que calienta mi corazón.",
        "Eres la brisa que refresca mi alma.",
        "Tu amor es el abrigo que me protege del frío.",
        "Eres la luna que ilumina mis noches.",
        "Tu sonrisa es la luz que ilumina mi día.",
        "Eres el refugio donde encuentro paz y amor.",
        "Tu presencia es el regalo que siempre esperé.",
        "Eres el mar donde quiero navegar eternamente.",
        "Tu amor es la fuerza que me impulsa a seguir adelante.",
        "Eres la estrella que ilumina mi camino.",
        "Tu mirada es el espejo donde veo mi alma.",
        "Eres la luz que ilumina mi oscuridad.",
        "Tu risa es la melodía que alegra mi corazón.",
        "Eres el amanecer que despierta mis días.",
        "Tu voz es la música que calma mi alma.",
        "Eres el sueño del que nunca quiero despertar.",
        "Tu amor es el motor que impulsa mi vida.",
        "Eres el horizonte que quiero alcanzar.",
        "Tu presencia es el ancla que me mantiene firme.",
        "Eres la chispa que enciende mi vida.",
        "Tu sonrisa es el sol que ilumina mis días.",
        "Eres la brisa que acaricia mi alma.",
        "Tu abrazo es el refugio donde encuentro paz.",
        "Eres el mar donde quiero navegar eternamente.",
        "Tu amor es el fuego que mantiene viva mi pasión.",
        "Eres el sueño del que nunca quiero despertar.",
        "Tu mirada es el mapa que guía mi camino.",
        "Eres la canción que mi corazón canta todos los días.",
        "Tu risa es el sol que ilumina mis días nublados.",
        "Eres la estrella que brilla en mi cielo nocturno.",
        "Tu amor es el puente que une nuestras almas.",
        "Eres el latido que mantiene vivo mi corazón.",
        "Tu presencia es el aire que respiro.",
        "Eres la flor que perfuma mi vida.",
        "Tu amor es la fuerza que me impulsa a seguir.",
        "Eres el libro que nunca me canso de leer.",
        "Tu voz es la melodía que alegra mis días.",
        "Eres la luz que guía mis pasos.",
        "Tu sonrisa es el refugio donde encuentro felicidad.",
        "Eres el abrazo que siempre anhelo.",
        "Tu amor es el faro que ilumina mi vida.",
        "Eres el sueño que nunca quiero dejar de soñar.",
        "Tu presencia es el sol que calienta mi corazón.",
        "Eres la brisa que refresca mi alma.",
        "Tu amor es el abrigo que me protege del frío.",
        "Eres la luna que ilumina mis noches.",
        "Tu sonrisa es la luz que ilumina mi día.",
        "Eres el refugio donde encuentro paz y amor.",
        "Tu presencia es el regalo que siempre esperé.",
        "Eres el mar donde quiero navegar eternamente.",
        "Tu amor es la fuerza que me impulsa a seguir adelante.",
        "Eres la estrella que ilumina mi camino.",
        "Tu mirada es el espejo donde veo mi alma.",
        "Eres la luz que ilumina mi oscuridad.",
        "Tu risa es la melodía que alegra mi corazón.",
        "Eres el amanecer que despierta mis días.",
        "Tu voz es la música que calma mi alma.",
        "Eres el sueño del que nunca quiero despertar.",
        "Tu amor es el motor que impulsa mi vida.",
        "Eres el horizonte que quiero alcanzar.",
        "Tu presencia es el ancla que me mantiene firme.",
        "Eres la chispa que enciende mi vida.",
        "Tu sonrisa es el sol que ilumina mis días.",
        "Eres la brisa que acaricia mi alma.",
        "Tu abrazo es el refugio donde encuentro paz.",
        "Eres el mar donde quiero navegar eternamente.",
        "Tu amor es el fuego que mantiene viva mi pasión.",
        "Eres el sueño del que nunca quiero despertar.",
        "Tu mirada es el mapa que guía mi camino.",
        "Eres la canción que mi corazón canta todos los días.",
        "Tu risa es el sol que ilumina mis días nublados.",
        "Eres la estrella que brilla en mi cielo nocturno.",
        "Tu amor es el puente que une nuestras almas.",
        "Eres el latido que mantiene vivo mi corazón.",
        "Tu presencia es el aire que respiro.",
        "Eres la flor que perfuma mi vida.",
        "Tu amor es la fuerza que me impulsa a seguir.",
        "Eres el libro que nunca me canso de leer.",
        "Tu voz es la melodía que alegra mis días."
    ];
    const content = document.getElementById("content");
    const randomIndex = Math.floor(Math.random() * verses.length);
    content.textContent = verses[randomIndex];
}